languageCode: en-us
markup:
  highlight:
    lineNos: true
    lineNumbersInTable: true
    style: vs
module:
  imports:
    - path: /data/github/on-nix/theme
permalinks:
  projects: /projects/:filename/
publishDir: docs
